### ISSUE TITLE
Crash / freeze upon starting up Alpha 6 with version installed

### ISSUE THREAD

**Issue by bedrockperson** [projectcomet64/metal-composer#2]
Installing composer 1.3 with alpha 6 crashes the app. Upon removing the .dll, and only the composer .dll, the app launches and runs without any issues. [See error message here](https://i.imgur.com/dfromp4.png) - clicking 'continue' will not close the app, but it will remain frozen on "Initializing addons" permanently.

**Comment by GlitchyPSIX** [comment]
It seems you are running MComposer under WINE. Please share error details (click the Details tab) and version of WINE (+ any winetricks packages you may have installed) in a reply to this comment.

_Additionally, I did not expect to see you here._

**Comment by bedrockperson** [comment]
> It seems you are running MComposer under WINE. Please share error details (click the Details tab) and version of WINE (+ any winetricks packages you may have installed) in a reply to this comment.

Yep, I don't know what I was thinking just posting a screenshot of the crash message without actually showing the error. The details are the following:

System.NullReferenceException: Object reference not set to an instance of an object.
 at M64MM.Utils.SettingsManager.GetSettingsGroup(String key, Boolean ensure)
  at M64MM.Utils.Core.<InitSettings>d__87.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__3(Object state)

Currently have Wine 1.8.6 installed. The only Winetrick I have installed relevant to this is MS .NET - since that was needed for the earlier 3.0 builds. I... unfortunately cannot actually see what version I have installed, I can only see the ones I HAVEN'T installed, I believe it's .NET 3.1 but I could be wrong, so, sorry I'm not more help there.

**Comment by GlitchyPSIX** [comment]
> System.NullReferenceException: Object reference not set to an instance of an object.
at M64MM.Utils.SettingsManager.GetSettingsGroup(String key, Boolean ensure)
at M64MM.Utils.Core.d__87.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.b__3(Object state)

This looks like a Config file problem. With M64MM3 closed, please delete the `config.json` file located in the M64MM3 folder, and reopen M64MM3. It should now find its way and create a new config file. Do reassign any settings you had saved. MComposer will create its own Settings group on startup (This probably conflicts with WINE, I'd have to dig deeper if simply deleting the file does not work).

I have observed M3 runs better on latest WINE (5.x), since you are using Mac I assume you are using Winebottler. In this case the latest version of Winebottler is 4.0.x, which you can find [here](https://winebottler.kronenberg.org) if your system supports it.

The minimum .NETFX version for M64MM3 to run is .NET 4.6.1, listed as `net461` in Winetricks. Any greater version should allow M3 to run.

_Additionally, Github emails me the initial version of any reply I am watching. I just want to let you know I do not forget._

**Comment by GlitchyPSIX** [comment]
One very important thing: Make a backup of your current config file. If it does not work, I'll have to ask you to send me your zipped M64MM3 folder along with the old config to try and recreate the problem in Linux.

**Comment by bedrockperson** [comment]
> > System.NullReferenceException: Object reference not set to an instance of an object.
> > at M64MM.Utils.SettingsManager.GetSettingsGroup(String key, Boolean ensure)
> > at M64MM.Utils.Core.d__87.MoveNext()
> > --- End of stack trace from previous location where exception was thrown ---
> > at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.b__3(Object state)
> 
> This looks like a Config file problem. With M64MM3 closed, please delete the `config.json` file located in the M64MM3 folder, and reopen M64MM3. It should now find its way and create a new config file. Do reassign any settings you had saved. MComposer will create its own Settings group on startup (This probably conflicts with WINE, I'd have to dig deeper if simply deleting the file does not work).

This did it, thank you.
